unique_nums = set()
num1 = int(input("enter first number \n"))
unique_nums.add(num1)
num2 = int(input("enter second number \n"))
unique_nums.add(num2)
num3 = int(input("enter third number \n"))
unique_nums.add(num3)
num4 = int(input("enter fourth number \n"))
unique_nums.add(num4)
num5 = int(input("enter fifth number \n"))
unique_nums.add(num5)
num6 = int(input("enter sixth number \n"))
unique_nums.add(num6)
num7 = int(input("enter seventh number \n"))
unique_nums.add(num7)
num8 = int(input("enter eightth number \n"))
unique_nums.add(num8)

print(unique_nums)